### ISSUE TITLE
FeOt and Fe3Fet vs FeO and Fe2O3

### ISSUE THREAD

**Issue by fboschetty** [PennyWieser/Thermobar#28]
I understand that the preference is for FeOt_liq and Fe3Fet_liq to avoid potential confusion between FeO and FeOt, but as you require the "t" to signify total it would be great if Thermobar could accept FeO_liq and Fe2O3_liq to accomodate outputs from Petrolog for example.  It only removes one relatively simple calculation but it would be nice.

Thanks,

Felix

**Comment by PennyWieser** [comment]
Hi Felix, you now have an option to have FeO_Liq and Fe2O3_Liq headings, but not also FeOt headings (as I had issues with peoples rounding when I allowed that). 

I have added this into the 5 minute example. My other python package, PySulfSat has a function specifically for importing Petrolog files, if that is what you want to do. Just pip install that. 

`# !pip install PySulfSat
import PySulfSat as ss
df_out=ss.import_data('PetrologCalculations.xlsx', Petrolog=True)`

I have just pushed version 1.0.8 to PyPI, once that badge appears both these changes should be incorperated. Let me know if that doesnt work!
