### ISSUE TITLE
convert_to_vesical Error

### ISSUE THREAD

**Issue by fboschetty** [PennyWieser/Thermobar#29]
I'm using the convert_to_vesical function but it returns the following error: 

[1](vscode-notebook-cell:/Users/FelixBoschetty/Documents/Spyder/ProbeData/OlivineEPMA.ipynb#X26sZmlsZQ%3D%3D?line=0) # Export for Vesical
----> [2](vscode-notebook-cell:/Users/FelixBoschetty/Documents/Spyder/ProbeData/OlivineEPMA.ipynb#X26sZmlsZQ%3D%3D?line=1) VESICAL = tb.convert_to_vesical(liq_comps=Glass_Thermo, T1=Ol_Liq_T, unit="Celcius")

File ~/opt/anaconda3/envs/Thermobar/lib/python3.10/site-packages/Thermobar/import_export.py:777, in convert_to_vesical(liq_comps, T1, unit, Fe3Fet_Liq)
    757 ''' Takes liquid dataframe in the format used for PyMME, and strips the _Liq string so that it can be input into VESical. Also removes the Fe3FeTcolumn, and appends temperature (converted from Kevlin to celcius)
    758 
    759 
   (...)
    774 
    775 '''
    776 df = liq_comps.copy()
--> 777 if unit is Kelvin:
    778     df['Temp'] = T1 - 273.15
    779 else:

NameError: name 'Kelvin' is not defined

The error happens because you require a string in the T1 option but the code is written to accept a variable named Kelvin. Instead line 777 should be replaced by:

if unit == "Kelvin":

Thanks,

Felix

**Comment by PennyWieser** [comment]
Thanks Felix, i've just fixed this (I had forgotten to change this when I changed something else). Just working on your import suggestion and then i'll push a new version with this change incorperated.

**Comment by fboschetty** [comment]
Thanks Penny, hope you have a good Christmas!
Felix

**Comment by PennyWieser** [comment]
Should work now, grab v.1.0.9
