### ISSUE TITLE
calculate_amp_plag_temp() combination issue

### ISSUE THREAD

**Issue by jlubbersgeo** [PennyWieser/Thermobar#35]
The `calculate_amp_plag_temp` function is creating the wrong number of combinations for the inputs. For example if there are 3 amphibole analyses and 2 plagioclase analyses the function currently outputs 972 temperatures, when it should output 6: one for each possible combination of temperatures. 

I believe it's a matrix math error in the following lines:
```python
# produces way too many outputs
Ked_trB = (27 / 64) * (XNa_M4 * XSi_T1 * XAn) / (XCa_M4 * XAl_T1 * XAb)
```
Since these are all dataframes its doing things different than if they were all numpy arrays:
```python
# produces the correct outputs in the form of a grid of amph x plag analyses
Ked_trB = (
        (27 / 64)
        * (np.array(XNa_M4) * np.array(XSi_T1) * np.array(XAn)[:, np.newaxis])
        / (np.array(XCa_M4) * np.array(XAl_T1) * np.array(XAb)[:, np.newaxis])
    )
```

**Comment by jlubbersgeo** [comment]
@PennyWieser currently fixing this right now just figured I'd give it an `official` issue

**Comment by PennyWieser** [comment]
<img width="680" alt="image" src="https://github.com/PennyWieser/Thermobar/assets/65668673/b29eb07f-82ea-4f5e-a74c-29bc87705ba8">
HAve added a melt matching function in v1.0.19, have also started adding checks for length of all inputs.
