### ISSUE TITLE
Specific Pandas Versions?

### ISSUE THREAD

**Issue by ThomasMGeo** [PennyWieser/Thermobar#37]
Running a course where a student ran into an issue with Thermobar with pandas version >2. These issues went away with version 1.3.5. 

Is this a known issue? Trying to debug further. 

Best,
-TM

**Comment by PennyWieser** [comment]
Not a known issue, but happy to debug if you can provide me with at least 1 and preferably 2 and 3:
1) The notebook and data they were using so I know what function/part of the package is failing. 
2) The error message
3) Their exact version of pandas if possible.

**Comment by ThomasMGeo** [comment]
Awesome! I am sure it's something on our end.

**Comment by ThomasMGeo** [comment]
I am going to close this, could not reproduce. Thanks for all the help!
