### ISSUE TITLE
Propagating analytical uncertainty with melts-matching functions

### ISSUE THREAD

**Issue by fboschetty** [PennyWieser/Thermobar#38]
Hi Penny, thought i'd quickly ask to make sure before I went ahead a wrote my own function. Is there already a fuction that will propagate analytical uncertainty using the add_noise function when doing simple melt matching?
As far as I can tell the output std is just the std for each cpx comp and its equilibrium melts. 

Thanks,

Felix

**Comment by PennyWieser** [comment]
Hi felix, exactly what did you have in mind? 
The way I would do this, is to take your say 10 liquids. Add noise to each of them using the add noise function, so now you have 1000 liquids, 100 per measured liquid.
Take your 10 Cpx, add noise to them too, then do melt matching between those noisy dataframes (1000 noisey liquids and 1000 noisy Cpx). 
The standard deviatoin is indeed the variation of 1 Cpx and the 10 melts it matches too.

**Comment by fboschetty** [comment]
Hi Penny,

I have a lot of cpx and liquid compositions for Villarrica and was trying to work out the best way to do both the simple and more complex (Scruggs type) cpx-liquid melts matching whilst incorporating the analytical uncertainties.

It seems like doing it in chunks and ensuring the sample_ids are sensible is the way forward. I'll give it a try and come back if I have any problems.

Thanks for the suggestions!

Felix
________________________________

**Comment by PennyWieser** [comment]
To clarify, I wanst advocating doing it in chunks per say, just an example of a simple case.

The code will handle doing it all at once, you'll just have to find something else to do while it chews through them. 

If say you have 100 liquids, making N=1000 noisy liquids per liquid, doing the same per Cpx, and then matching them all together will incorperate your analytical uncertainty. You may eventually hit a memory issue on your computer, but I am yet to hit one with similarly large calculations (this is how others have been using Thermobar to do this workflow).
