### ISSUE TITLE
Need Onnx and Pkl

### ISSUE THREAD

**Issue by fboschetty** [PennyWieser/Thermobar#39]
Hi Penny,

I'm using Thermobar 1.0.29, but have also tried updating and using 1.0.31.
In a clean conda env with just Thermobar pip installed and Jupyter I cannot run the Wang and Jorgenson thermobarometers and get the following error: You havent installed the extra package to get onnx and pkl files for machine learning. See README.

I have tried conda installing onnx but that didn't fix it. 

Thanks,

Felix

**Comment by PennyWieser** [comment]
Hi Felix
have you done this:
#!pip install "https://github.com/PennyWieser/Thermobar_onnx/archive/refs/tags/v.0.0.4.zip"
From here

https://thermobar.readthedocs.io/en/latest/Examples/Cpx_Cpx_Liq_Thermobarometry/MachineLearning_Cpx_Liq_Thermobarometry.html

These are too big to put in the other PyPI (See the paper)..

you probably need sklearn 1.2, big changes are causing issues with the pkls

**Comment by fboschetty** [comment]
Ah no sorry, I managed to miss that. Could it be put on the installation page of the docs?

Thanks,

Felix
