### ISSUE TITLE
Add_Noise Error

### ISSUE THREAD

**Issue by fboschetty** [PennyWieser/Thermobar#40]
Hi!

i'm attempting to MC propagate some analytical errors for cpx-only tb.

I have two dataframes, one with headers: oxide_Cpx and another with relative errors: oxide_Cpx_Err.
I've put them in the spreadsheet attached.

When I attempt to use the add_noise function I get the following error:
``` python
tb.noise_averaging.add_noise_sample_1phase(phase_comp=Cpx, phase_err=Cpx_err, phase_err_type="Perc", duplicates=1_000, err_dist="Normal")
```
<img width="939" alt="Screenshot 2023-12-01 at 22 20 33" src="https://github.com/PennyWieser/Thermobar/assets/64596942/8e6a762f-9f9c-441e-97f0-a174f7e4c6bd">

Initially I had other errors, but when I ensured that all my sample_ids were unique they went away.

Thanks again,

Felix

[Cpx_Error_Example.xlsx](https://github.com/PennyWieser/Thermobar/files/13532016/Cpx_Error_Example.xlsx)

**Comment by PennyWieser** [comment]
Hi Felix can you attach your notebook too pls.

**Comment by fboschetty** [comment]
It won't let me upload a ipynb but it's only a couple of lines. This is Thermobar 1.0.31.

import pandas as pd
import Thermobar as tb
tb.__version__

path = "Cpx_Error_Example.xlsx"

Cpx_data = pd.read_excel(path, sheet_name="Data", header=0)
Cpx_err = pd.read_excel(path, sheet_name="Error", header=0)

n_MC = 1_000

Cpx_MC = tb.noise_averaging.add_noise_sample_1phase(phase_comp=Cpx_data, phase_err=Cpx_err, phase_err_type="Perc", duplicates=n_MC, err_dist="Normal")

**Comment by fboschetty** [comment]
I just checked and I had FeO_Cpx_Err rather than FeOt_Cpx_Err but changing it made no difference.

**Comment by PennyWieser** [comment]
Hi Felix,
First, please make sure you are using the thermobar loading functions, not just pd.read_excel. 

the whole point of these is to check you are passing the right columns Thermobar knows how to deal with. I cannot guarantee results if you just load in a random dataframe and bypass all my checks. 
For example, if you had used this, you would catch the FeO error
<img width="693" alt="image" src="https://github.com/PennyWieser/Thermobar/assets/65668673/abb01810-d31a-4aaa-bda2-fde94fcb7c8d">


Second, err_dist='normal' not 'Normal'. I will add a TypeError to spit out an error if people do this again. 

That works now. However, there was actually a real bug if you had used the right column labels (Sample_Id_Cpx_Err was what yours was, not Sample_ID_Cpx_Err). I will work on getting it to work with the column labels for the error if it was labelled right (Pandas 1-2 conversion is causing big issues), but with your spreadsheets and the code below it should work now.

**Comment by PennyWieser** [comment]
`path = "Cpx_Error_Example.xlsx"
out_err=pt.import_excel_errors(path, sheet_name='Error')
Cpx_err=out_err['Cpxs_Err']


out=pt.import_excel(path, sheet_name="Data")
my_input=out['my_input']
Cpx_data=out['Cpxs']

n_MC = 1000

Cpx_MC = tb.noise_averaging.add_noise_sample_1phase(phase_comp=Cpx_data, phase_err=Cpx_err, phase_err_type="Perc", duplicates=n_MC, err_dist="normal")`

**Comment by PennyWieser** [comment]
``path = "Cpx_Error_Example.xlsx"
out_err=pt.import_excel_errors(path, sheet_name='Error')
Cpx_err=out_err['Cpxs_Err']


out=pt.import_excel(path, sheet_name="Data")
my_input=out['my_input']
Cpx_data=out['Cpxs']

n_MC = 1000

Cpx_MC = tb.noise_averaging.add_noise_sample_1phase(phase_comp=Cpx_data, phase_err=Cpx_err, phase_err_type="Perc", duplicates=n_MC, err_dist="normal")``

**Comment by PennyWieser** [comment]
path = "Cpx_Error_Example.xlsx"
out_err=pt.import_excel_errors(path, sheet_name='Error')
Cpx_err=out_err['Cpxs_Err']


out=pt.import_excel(path, sheet_name="Data")
my_input=out['my_input']
Cpx_data=out['Cpxs']

n_MC = 1000

Cpx_MC = tb.noise_averaging.add_noise_sample_1phase(phase_comp=Cpx_data, phase_err=Cpx_err, phase_err_type="Perc", duplicates=n_MC, err_dist="normal")

**Comment by fboschetty** [comment]
Sorry for the fuss, I know the loading in functions are better, but often I want to filter, or combine datasets without exporting to a spreadsheet then loading it back in.

Thanks for all the help!

Felix

**Comment by PennyWieser** [comment]
You need to either load everything thro thermobar functions before you combine, or at the final step before calcs. I really can't promise things will work otherwise. Or, if you really want to do that, you need to implement the checks in the function 'import_excel' for yourself.  The whole point of the loading structure was to catch many of the most common bugs  I see

Would it help if the import excel function had the option to load in a dataframe, not an excel sheet?

**Comment by fboschetty** [comment]
It would help if that were the case, as it would mean I wouldn't have to write to excel, but its not reasonable to implement just for me.

As an aside, with above the code works when I use 'Sample_Id_Cpx_Err' for the errors (note lower case d) and 'Sample_ID_Cpx' for the data. But not if they are both capital. I've always used a capital D for thermobar and never had problems. Am I missing something obvious yet again?

**Comment by PennyWieser** [comment]
Yup that's a big one fixed. It wasn't seeing the column of you used Id. But
if it was pandas was having a division problem. Sorted now (I drop the ID
column on the noise before dividing, else it's trying to divide a string by
another string (Id column in cpx by ID column in data). Only an issue for
perc errors.

It's be a one line tweak to the import function.

**Comment by fboschetty** [comment]
Then yes that would be a great addition.

I'm also now having problems with using the Jorgenson Cpx-only barometer and the add_noise data. 
I gathered I need to use the 'return_input=True' flag to preserve the "Sample_ID_Cpx_Num" column for later averaging. but when I do I get the error: local variable 'P_kbar' referenced before assignment.

I can get around this by manually appending the "Sample_ID_Cpx_Num" column to the result.

I don't have this when I use the same flag but for the Wang Cpx-only barometer.

**Comment by PennyWieser** [comment]
Hi Felix,
Can you post the code that causes an issue and the error message.
Had to do a major package re-arrangment to support pandas2 and sklearn2.1+
so there are some bugs sitting around.

**Comment by fboschetty** [comment]
Using the same spreadsheet as above.
``` python
path = "Cpx_Error_Example.xlsx"
out_err=tb.import_excel_errors(path, sheet_name='Error')
Cpx_err=out_err['Cpxs_Err']

out=tb.import_excel(path, sheet_name="Data")
my_input=out['my_input']
Cpx_data=out['Cpxs']

n_MC = 1000

Cpx_MC = tb.noise_averaging.add_noise_sample_1phase(phase_comp=Cpx_data, phase_err=Cpx_err, phase_err_type="Perc", duplicates=n_MC, err_dist="normal")

Cpx_Only_P_J2022_MC = tb.clinopyroxene_thermobarometry.calculate_cpx_only_press(cpx_comps=Cpx_MC, equationP="P_Jorgenson2022_Cpx_only", return_input=True)
Cpx_Only_P_W2021_MC = tb.clinopyroxene_thermobarometry.calculate_cpx_only_press(cpx_comps=Cpx_MC, equationP="P_Wang2021_eq1", return_input=True)

Cpx_Only_P_J2022_MC_Stats = tb.av_noise_samples_series(calc=Cpx_Only_P_J2022_MC["P_kbar_calc"], sampleID=Cpx_Only_P_J2022_MC["Sample_ID_Cpx_Num"])
Cpx_Only_P_W2021_MC_Stats = tb.av_noise_samples_series(calc=Cpx_Only_P_W2021_MC["P_kbar_calc"], sampleID=Cpx_Only_P_W2021_MC["Sample_ID_Cpx_Num"])
```

Gives:

<img width="984" alt="Screenshot 2023-12-02 at 17 03 00" src="https://github.com/PennyWieser/Thermobar/assets/64596942/e98e4fd2-e0b4-4542-b2a9-74141feb0c19">

**Comment by PennyWieser** [comment]
okay, fixing this now. It should now be eq_tests=True for consistency with other functions. 
If you are in a hurry you can just ste eq_tests=False and by hand merge cpx_comps with the outputs. 
I'm just fixing some onnx runtime bugs with the latest sklearn then will push an update. 
Update in ~10 mins and see if it works.

**Comment by fboschetty** [comment]
Okay no rush at all!

Thanks, Penny!

**Comment by PennyWieser** [comment]
1.0.34 shuld fix this. (just pushed)
