### ISSUE TITLE
Add Noise Error: Typo Means it Searches for Liquid Compositions.

### ISSUE THREAD

**Issue by fboschetty** [PennyWieser/Thermobar#43]
Dear Penny,

I'm having some trouble with setting up some MC compositions for some spinel analyses.
I'm having several issues but i'd thought I'd start with this one.

I get an error that occurs because I have duplicate sample names.
I've looked through the code and I think the error is in line 343 of noise_averaging.py:

```python
Sample_c.loc[i, 'Sample_ID_Liq']=Sample_c['Sample_ID_Liq'].iloc[i]+'_'+str(TEST[i])
```

Here where it says Liq in the string it should read {} to be consistent with the rest of the code.
I can't see this anywhere else in the script so I think changing that should sort it.

I would do it myself but I don't really know how GitHub works. I'll look into it for the future.

Felix

**Comment by fboschetty** [comment]
I've copied the function over and changed the line to read:

```python
Sample_c.loc[i, 'Sample_ID_{}'.format(elx)]=Sample_c['Sample_ID_{}'.format(elx)].iloc[i]+'_'+str(TEST[i])
```

and it does indeed fix it. 

Felix

**Comment by fboschetty** [comment]
I think I have correctly submitted a pull request to fix this.

Felix

**Comment by PennyWieser** [comment]
Hi Felix, sorry can you submit a spreadsheet and a .py or .ipynb showing this bug first? The not allowing duplicate names was important for other functionality (how they are later averaged).

**Comment by fboschetty** [comment]
Hi Penny, so i just meant that it only occurs when I have duplicate sample names. That allowed me to work out where the typo was. The fix was just a matter of changing some of the strings that contained 'Liq' to use the identified phase type using string formatting and the variable elx as it is in the rest of the file. 

I am very sure this is just a typo and isn't meant to read Liq.

**Comment by PennyWieser** [comment]
Ah okay gottcha. Yes, it was a typo, have merged pull request now.
