### ISSUE TITLE
Spinel Compositions Limited Oxide Options

### ISSUE THREAD

**Issue by fboschetty** [PennyWieser/Thermobar#44]
Hi Penny,

Problem no. 2. I have measured some 'more exotic' minors for my spinel analyses but these aren't picked up when i load them using import_excel.

I'm not sure if it's possible to just add extra oxides in the import_export.py script or if this might have a knock-on effect down the line somewhere.

I don't analyse Na and K for my spinel analyses and the import function can deal with that so maybe adding them and then having others not use them isn't a big problem.

I measure:
Si, Ti, Cr, Al, Fe, Mg, Mn, Ca, Ni, Zn, Co, Nb, V, Cu. 

In my past coding attempts I have used a user-defined list of oxides, which consults a csv for molar mass, no. oxygens etc, which allows for more flexibility when importing. I suspect there's a way to automatically populate this csv/text file from a periodic table library.

I understand that keeping things rigid reduces the scope for errors and users, myself included, making mistakes. But happy to discuss if you like the idea of making imports and exports more flexible.

Felix

**Comment by PennyWieser** [comment]
Hi Felix,
What would be the reason for wanting these? None of the spinel models had these in their calibration datasets I dont think, so a) they dont appear in the empirical parameterizatoins b) if you normalize cations with extra elements that werent in the cali datasets, you end up with a different solution. 

Everytime a model appears that includes a new oxide directly in its parameterization or method of normalizing data, i can add it to the imports. Then, the other models that dont use that element i will drop the oxide before normalizing etc.

**Comment by fboschetty** [comment]
Hi Penny,

I'm using your add phase error to run some MC bits prior to running my own code. So perhaps I can just live with using my own version of thermobar for this purpose in the short term.

I am trying to estimate fO2 by using a Sp-Melt Fe2/Fe3 relationships. As I am using stoichiometry to calculate Fe2/3, the calculated Fe2O3 is skewed if you don't measure all constituent elements, hence the exotic list.

It would be good to include some Ol-Sp and Sp-Liq oxybarometers in thermobar, i'd be more than happy to help code them up.

Felix

**Comment by PennyWieser** [comment]
Ah, that makes sense. The add_noise_sample_1phase function is certainly clunkier than it needs to be (was written by 2021 Penny prior to GPT) - particularly as it is trying to support various options like just noising one element, lots of elements, from a dataframe etc. 

If you are just trying to Monte-Carlo a load of different elements, and that list is changing, you could easily adapt that function to just iterate over as many columns as you have columns instead of listing them in L496-567 (again, I could fix this, but its functional for now)- I was trying to make it just support out inputs and by doing it like this, people get errors they can trace easier (and I was being lazy). 


What ol-sp and Sp-Liq oxybarometers were you thinking should be added?

**Comment by fboschetty** [comment]
Right now i'm using a combination of Droop 1987, Maurel and Maurel 1982 and Borisov et al., 2018 to do the following:
1. estimate spinel Fe2/3
2. calculate coexisting liquid Fe2/3
3. convert this into an oxygen fugacity buffer & offset.

It would be useful to have the following in thermobar:
- Ballhaus et al., 1991 (erratum 1994)
- Shishkina et al., 2018 (V ol-sp exchange)
- The above Maurel Maurel 1982 Sp-Liq Fe2/3 exchance
- Borisov et al., 2018 alternative to Kress and Carmichael 1991.

Felix

**Comment by PennyWieser** [comment]
Hi Felix, we should chat offline about this (next few weeks are mad with grant proposals, but hoping feb is more free).
One of the requirements  for the models in Thermobar being in Thermobar was that there was an externally validated calculation tool already in existence - I learnt from VESical that so many paper contain typos (e..g see this new paper about Duan and Zhang, CO2-H2O EOS) - https://www.jstage.jst.go.jp/article/jmps/118/1/118_221224a/_article
I didnt want to be responsible for perpetuating errors/typos in equations/unclear ways of preprocessing data. Each model is benchmarked and that benchmark is provided. 
Not sure how many of those would fit that requirement?

If they do, and you wanted to contribute them, we should chat about how you could get credit for that (sadly, the way we publish these open source tools makes it hard for later contributors to gain credit). One option would be if you are working on a paper that heavily uses these, to say in that that you contributed the code to Thermobar, and we can add a note that if you use those models, you should cite Thermobar (for my labor maintaining the distribution of the package) and your paper for the addition of these models (e.g., we use the method of Ballhaus et al. 1991 provided by Boschetty et al. 2024 implemented in Thermobar, Wieser et al. 2022).

I can also help with the conversion to Thermobar and would like to oversee changes to large packages like import packages given how many headaches they give me when people use them wrong (you wont believe how many of the issues I deal with are just people loading empty data or whatever - e.g. https://github.com/PennyWieser/Thermobar/issues/42)

**Comment by fboschetty** [comment]
Great. I'll close this issue and shoot you an email. We can find a time in Feb to discuss.

Felix
