### ISSUE TITLE
Clarification with Jorgenson 2022 (Cpx-only)

### ISSUE THREAD

**Issue by dyspence** [PennyWieser/Thermobar#46]
Hi Penny,

This isn't a coding issue, but a reporting clarification. In Jorgenson's R package, the default P and T chosen from the machine learning models is the mean, but the median is also reported. In Thermobar, both P_kbar_calc (T_K_calc) and Median_Trees are reported. In this case, is P_kbar_calc/T_K_calc referring to the mean?

Thanks in advance!
Dylan

**Comment by PennyWieser** [comment]
Hi Dylan,
the P_kbar and T_K is mean, as that is the sklearn default. We also include the median as a separate column as Jorgenson wanted that.
