### ISSUE TITLE
support for pathlib Path objects in import_excel()

### ISSUE THREAD

**Issue by jlubbersgeo** [PennyWieser/Thermobar#47]
In an effort to make a lot of my scripts more language agnostic and because Windows and Mac OS have different string representations of filepaths, I've started using `pathlib.Path` objects:

```python
from pathlib import Path
input_path = Path(r"C:\Users\jlubbers\...\Great_sitkin_petrology\EPMA")
```
Then using `pandas` no matter the OS we can use the `pathlib.Path` and the spreadsheet name:
```python
import pandas as pd
outlier_data = pd.read_excel(input_path / "GS_px_cleaned_working.xlsx")
```
However in Thermobar we're met with an error:
```python
outlier_data = pt.import_excel(input_path / "GS_px_cleaned_working.xlsx", sheet_name = 'rejects')
```
```bash
[309](file:///C:/Users/jlubbers/AppData/Local/mambaforge/envs/everyday/lib/site-packages/Thermobar/import_export.py:309) def import_excel(filename, sheet_name, sample_label=None, GEOROC=False, suffix=None):
   (...)
--> [338](file:///C:/Users/jlubbers/AppData/Local/mambaforge/envs/everyday/lib/site-packages/Thermobar/import_export.py:338)     if 'csv' in filename:
    [339](file:///C:/Users/jlubbers/AppData/Local/mambaforge/envs/everyday/lib/site-packages/Thermobar/import_export.py:339)         my_input = pd.read_csv(filename)
    [341](file:///C:/Users/jlubbers/AppData/Local/mambaforge/envs/everyday/lib/site-packages/Thermobar/import_export.py:341)     elif 'xls' in filename:

TypeError: argument of type 'WindowsPath' is not iterable
```
Looking at the source code for `import_excel()`, it looks like the conditional for checking for filetype is what is causing the error. I think something like just checking for a `pathlib` object and converting it to a string at the beginning would work!
```python
import pathlib
filename = input_path / "GS_px_cleaned_working.xlsx"

if isinstance(filename, pathlib.PurePath):
    inpath = filename.__str__()

pt.import_excel(inpath, sheet_name= "rejects") # <--- WORKS!

```

While all this could be done outside the function, it would be cleaner and maybe make demo examples for users that are on any OS easier in the future

**Comment by PennyWieser** [comment]
Hi Jordan, this sounds great, but I dont have a mac to be able to test this. Would you be able to grab a local version, make the edit, test it works, and then do a pull request?

**Comment by jlubbersgeo** [comment]
I'm also on a windows machine `wompwomp`. But I _think_ the `PurePath` takes care of this based off [this](https://stackoverflow.com/questions/58647584/how-to-test-if-object-is-a-pathlib-path) thread.

**Comment by PennyWieser** [comment]
Ah okay. I'll find a Mac to test on to be sure!

**Comment by PennyWieser** [comment]
Okay, pushed a new version (not to PyPi , just to github, 1.0.35) - waiting to test on mac, now you can either do it the old way
out=pt.import_excel('ArcPL_Filtered_Dataset.xlsx', sheet_name='Sheet1')
Or then add out=pt.import_excel('ArcPL_Filtered_Dataset.xlsx', sheet_name='Sheet1', path=my_path)
where my_path = input_path = Path(r"C:\Users\penny\Box\Postdoc\MyBarometers\Thermobar_outer\docs\Examples\Cpx_Cpx_Liq_Thermobarometry")

**Comment by jlubbersgeo** [comment]
lovely! ✨ 🎉  

Thanks for all your hard work!
